version: '3'

services: 
    n_queens:
        build: ./
        command: python main.py
        depends_on: 
            - db
        stdin_open: true # docker run -i
        tty: true        # docker run -t
    db:
        image: postgres
        env_file:
            - database.env
        ports: 
            - "5437:5432"
        volumes:
            - database-data:/var/lib/postgresql/data
volumes:
    database-data:
    