version: '3'

services: 
    postgres_db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: default
            POSTGRES_USER: default
            POSTGRES_DB: default
        ports: 
            - "5437:5437"
    n_queens:
        build: ./
        command: python main.py
        depends_on: 
            - postgres_db
        stdin_open: true # docker run -i
        tty: true        # docker run -t
    